apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nodejs-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: nodejs-k8s-helm  
    spec:                  
      containers: 
      - name: nodejs-k8s-helm 
        image: nodejs-k8s-helm:v1
        ports:
        - containerPort: 3000
